### PR TITLE
Add starring feature

### PR DESCRIPTION
**Pull request by samuelli**

### CODE REVIEW

**Comment by abdonrd** [comment]
screen shot 2016-11-02 at 09 34 28

All this permission is required? 😕

**Comment by abdonrd** [comment]
cc @samuelli :)

**Comment by samuelli** [comment]
@abdonrd: Yeah, it's super unfortunate :(

https://developer.github.com/v3/oauth/#scopes
"Also required for starring public repositories."

I've already filed multiple feature requests for alternative workarounds like starring as a separate scope

**Comment by abdonrd** [comment]
@samuelli thanks for the explication! :(

**Pull request merged**
