### PR TITLE
Enable redirect on beta.webcomponents.org

### PR DESCRIPTION
**Pull request by dstockwell**

### CODE REVIEW

**Comment by abdonrd** [comment]
@samuelli now maybe the repository needs a rename? 😁

**Comment by samuelli** [comment]
@abdonrd Yes! Any ideas? :)

**Comment by samuelli** [comment]
Maybe webcomponents/www will be fine?

**Comment by abdonrd** [comment]
@samuelli I propose `webcomponents.org`. But `www` is okey for me too!

**Pull request merged**
